"""stage c content ops tables

Revision ID: 0d5f7d7f93a0
Revises: 1f4dadfdfdba
Create Date: 2026-08-03 13:00:31.675341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d5f7d7f93a0'
down_revision: Union[str, Sequence[str], None] = '1f4dadfdfdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hallmark_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'flagged_fake', name='hallmarkstatus'), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_manifest_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_manifest_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['set_manifest_id'], ['set_manifest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_manifest_member_set_manifest_id'), 'set_manifest_member', ['set_manifest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_manifest_member_set_manifest_id'), table_name='set_manifest_member')
    op.drop_table('set_manifest_member')
    op.drop_table('set_manifest')
    op.drop_table('hallmark_reference')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS hallmarkstatus")
