"""stage b condition and provenance

Revision ID: 1f4dadfdfdba
Revises: 5e6f046bb5f3
Create Date: 2026-08-03 12:42:55.850900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f4dadfdfdba'
down_revision: Union[str, Sequence[str], None] = '5e6f046bb5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_signed_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('convention_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('convention_date', sa.Date(), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('witnessed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['witnessed_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_signed_provenance_item_id'), 'guest_signed_provenance', ['item_id'], unique=False)
    op.create_table('pin_condition',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('moon_gap', sa.Enum('none', 'slight', 'moderate', 'wide', name='moongap'), nullable=False),
    sa.Column('pin_back_original', sa.Boolean(), nullable=False),
    sa.Column('post_straightness', sa.Enum('straight', 'bent', 'replaced', name='poststraightness'), nullable=False),
    sa.Column('enamel_chip_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('provenance_anchor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('proof_type', sa.Enum('receipt', 'order_confirmation', 'badge_photo', 'other', name='prooftype'), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('app_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provenance_anchor_item_id'), 'provenance_anchor', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provenance_anchor_item_id'), table_name='provenance_anchor')
    op.drop_table('provenance_anchor')
    op.drop_table('pin_condition')
    op.drop_index(op.f('ix_guest_signed_provenance_item_id'), table_name='guest_signed_provenance')
    op.drop_table('guest_signed_provenance')
    # ### end Alembic commands ###

    # See the Stage A migration — autogenerate doesn't drop Postgres's native
    # ENUM types on its own.
    for enum_name in ("moongap", "poststraightness", "prooftype"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
