"""auth: email, invites, magic link tokens, sessions

Revision ID: 24fcdac671b5
Revises: 3316d782a232
Create Date: 2026-08-10 18:11:20.299768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24fcdac671b5'
down_revision: Union[str, Sequence[str], None] = '3316d782a232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pending_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_token_email'), 'magic_link_token', ['email'], unique=False)
    op.create_index(op.f('ix_magic_link_token_token'), 'magic_link_token', ['token'], unique=True)
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_code'), 'invite', ['code'], unique=True)
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_token'), 'user_session', ['token'], unique=True)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.add_column('app_user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_column('app_user', 'email')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_token'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_invite_code'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_magic_link_token_token'), table_name='magic_link_token')
    op.drop_index(op.f('ix_magic_link_token_email'), table_name='magic_link_token')
    op.drop_table('magic_link_token')
    # ### end Alembic commands ###
