"""stage a core catalog

Revision ID: 5e6f046bb5f3
Revises: 
Create Date: 2026-08-03 10:29:53.534441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e6f046bb5f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('member', 'council', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('franchise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franchise_name'), 'franchise', ['name'], unique=True)
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_type_name'), 'item_type', ['name'], unique=True)
    op.create_table('rarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rarity_name'), 'rarity', ['name'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('rarity_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('redemption_status', sa.Enum('not_applicable', 'unredeemed', 'redeemed', 'redeemed_elsewhere', 'orphaned', name='redemptionstatus'), nullable=False),
    sa.Column('exclusive_channel', sa.Enum('goody_bag', 'on_site_store', 'employee_only', 'community_rep_gift', name='exclusivechannel'), nullable=True),
    sa.Column('trade_stock', sa.Boolean(), nullable=False),
    sa.Column('edition_number', sa.Integer(), nullable=True),
    sa.Column('edition_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_owner_id'), 'item', ['owner_id'], unique=False)
    op.create_table('item_tag',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.Enum('item', 'packaging', 'coa', 'condition', 'other', name='phototype'), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_item_id'), 'photo', ['item_id'], unique=False)
    op.create_table('value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_history_item_id'), 'value_history', ['item_id'], unique=False)
    # ### end Alembic commands ###

    # Starter rows so the catalog is usable without hand-editing the database —
    # adding more franchises/types/rarities later is just another row, per the
    # lookup-table design call in the Stage A proposal.
    franchise = sa.table("franchise", sa.column("name", sa.String))
    op.bulk_insert(
        franchise,
        [
            {"name": "Blizzard Entertainment"},
            {"name": "Star Trek"},
            {"name": "Other Sci-Fi"},
        ],
    )

    item_type = sa.table("item_type", sa.column("name", sa.String))
    op.bulk_insert(
        item_type,
        [
            {"name": "Enamel Pin"},
            {"name": "Statue"},
            {"name": "Trading Card"},
            {"name": "Apparel"},
            {"name": "Replica Prop"},
            {"name": "Other"},
        ],
    )

    rarity = sa.table("rarity", sa.column("name", sa.String), sa.column("sort_order", sa.Integer))
    op.bulk_insert(
        rarity,
        [
            {"name": "Common", "sort_order": 0},
            {"name": "Uncommon", "sort_order": 1},
            {"name": "Rare", "sort_order": 2},
            {"name": "Limited / Chase", "sort_order": 3},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_history_item_id'), table_name='value_history')
    op.drop_table('value_history')
    op.drop_index(op.f('ix_photo_item_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_table('item_tag')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_rarity_name'), table_name='rarity')
    op.drop_table('rarity')
    op.drop_index(op.f('ix_item_type_name'), table_name='item_type')
    op.drop_table('item_type')
    op.drop_index(op.f('ix_franchise_name'), table_name='franchise')
    op.drop_table('franchise')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###

    # Autogenerate doesn't drop Postgres's native ENUM types on its own —
    # without this, re-running upgrade after a downgrade fails with
    # "type already exists".
    for enum_name in ("userrole", "redemptionstatus", "exclusivechannel", "phototype"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
