"""connect pillar: contacts trust checkins trades vouches reports community posts

Revision ID: 6a2177d13cd0
Revises: 3316d782a232
Create Date: 2026-08-09 21:06:15.326330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a2177d13cd0'
down_revision: Union[str, Sequence[str], None] = '3316d782a232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Enum('showcase', 'trade', 'seeking', name='posttype'), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_post_user_id'), 'community_post', ['user_id'], unique=False)
    op.create_table('contact',
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('tier_1', 'tier_2', 'tier_3', name='connecttier'), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_user_id', 'to_user_id')
    )
    op.create_table('convention_check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('convention_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('convention_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('geofence', 'manual', name='checkinmethod'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convention_check_in_user_id'), 'convention_check_in', ['user_id'], unique=False)
    op.create_table('exchange_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_user_id', sa.Integer(), nullable=False),
    sa.Column('counterpart_user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['counterpart_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_session_counterpart_user_id'), 'exchange_session', ['counterpart_user_id'], unique=False)
    op.create_index(op.f('ix_exchange_session_initiator_user_id'), 'exchange_session', ['initiator_user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'soft_flagged', 'resolved', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reported_user_id'), 'report', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_report_reporter_user_id'), 'report', ['reporter_user_id'], unique=False)
    op.create_table('trade_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_user_id', sa.Integer(), nullable=False),
    sa.Column('counterpart_user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_by_counterpart', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['counterpart_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_record_counterpart_user_id'), 'trade_record', ['counterpart_user_id'], unique=False)
    op.create_index(op.f('ix_trade_record_initiator_user_id'), 'trade_record', ['initiator_user_id'], unique=False)
    op.create_table('community_post_item',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'item_id')
    )
    op.create_table('vouch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_record_id', sa.Integer(), nullable=False),
    sa.Column('voucher_user_id', sa.Integer(), nullable=False),
    sa.Column('vouched_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_record_id'], ['trade_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vouched_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['voucher_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouch_trade_record_id'), 'vouch', ['trade_record_id'], unique=False)
    op.create_index(op.f('ix_vouch_vouched_user_id'), 'vouch', ['vouched_user_id'], unique=False)
    op.create_index(op.f('ix_vouch_voucher_user_id'), 'vouch', ['voucher_user_id'], unique=False)
    op.add_column(
        'app_user',
        sa.Column('auto_connect_at_conventions', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'auto_connect_at_conventions')
    op.drop_index(op.f('ix_vouch_voucher_user_id'), table_name='vouch')
    op.drop_index(op.f('ix_vouch_vouched_user_id'), table_name='vouch')
    op.drop_index(op.f('ix_vouch_trade_record_id'), table_name='vouch')
    op.drop_table('vouch')
    op.drop_table('community_post_item')
    op.drop_index(op.f('ix_trade_record_initiator_user_id'), table_name='trade_record')
    op.drop_index(op.f('ix_trade_record_counterpart_user_id'), table_name='trade_record')
    op.drop_table('trade_record')
    op.drop_index(op.f('ix_report_reporter_user_id'), table_name='report')
    op.drop_index(op.f('ix_report_reported_user_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_exchange_session_initiator_user_id'), table_name='exchange_session')
    op.drop_index(op.f('ix_exchange_session_counterpart_user_id'), table_name='exchange_session')
    op.drop_table('exchange_session')
    op.drop_index(op.f('ix_convention_check_in_user_id'), table_name='convention_check_in')
    op.drop_table('convention_check_in')
    op.drop_table('contact')
    op.drop_index(op.f('ix_community_post_user_id'), table_name='community_post')
    op.drop_table('community_post')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS posttype")
    op.execute("DROP TYPE IF EXISTS connecttier")
    op.execute("DROP TYPE IF EXISTS checkinmethod")
    op.execute("DROP TYPE IF EXISTS reportstatus")
