"""wishlist priority tags

Revision ID: aca9cfaee0da
Revises: fbca36e46362
Create Date: 2026-08-08 17:11:24.624521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca9cfaee0da'
down_revision: Union[str, Sequence[str], None] = 'fbca36e46362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Unlike CREATE TABLE, ADD COLUMN doesn't auto-create a new Postgres
    # ENUM type — has to happen explicitly first.
    op.execute("CREATE TYPE wishlistpriority AS ENUM ('grail', 'filler')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_entry', sa.Column('priority', sa.Enum('grail', 'filler', name='wishlistpriority', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_entry', 'priority')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS wishlistpriority")
