"""stage d acquire

Revision ID: fbca36e46362
Revises: 0d5f7d7f93a0
Create Date: 2026-08-03 14:34:57.867921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbca36e46362'
down_revision: Union[str, Sequence[str], None] = '0d5f7d7f93a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watcher_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_type', sa.Enum('official_api', 'rss', 'public_scrape_no_login', name='watcheraccesstype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watcher_source_name'), 'watcher_source', ['name'], unique=True)
    op.create_table('wishlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('variant_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condition_floor', sa.Enum('any', 'loose_acceptable', 'sealed_mib', name='conditionfloor'), nullable=False),
    sa.Column('coa_required', sa.Boolean(), nullable=False),
    sa.Column('price_ceiling', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'fulfilled', name='wishliststatus'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_entry_user_id'), 'wishlist_entry', ['user_id'], unique=False)
    op.create_table('watcher_hit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('watcher_source_id', sa.Integer(), nullable=False),
    sa.Column('external_listing_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('listing_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['watcher_source_id'], ['watcher_source.id'], ),
    sa.ForeignKeyConstraint(['wishlist_entry_id'], ['wishlist_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watcher_hit_wishlist_entry_id'), 'watcher_hit', ['wishlist_entry_id'], unique=False)
    # ### end Alembic commands ###

    # The four watcher sources locked in SCOPE.md. No login/session column
    # exists on this table at all — that's the standing architectural rule,
    # not an omission. Adding a fifth source later (once it clears
    # legality/ToS review) is a new row here, not a code change.
    access_type_enum = sa.Enum(
        "official_api", "rss", "public_scrape_no_login",
        name="watcheraccesstype", create_type=False,
    )
    watcher_source = sa.table(
        "watcher_source",
        sa.column("name", sa.String),
        sa.column("access_type", access_type_enum),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        watcher_source,
        [
            {"name": "eBay", "access_type": "official_api", "is_active": True},
            {"name": "Craigslist", "access_type": "rss", "is_active": True},
            {"name": "Blizzard Gear Store", "access_type": "public_scrape_no_login", "is_active": True},
            {"name": "Facebook Marketplace", "access_type": "public_scrape_no_login", "is_active": True},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watcher_hit_wishlist_entry_id'), table_name='watcher_hit')
    op.drop_table('watcher_hit')
    op.drop_index(op.f('ix_wishlist_entry_user_id'), table_name='wishlist_entry')
    op.drop_table('wishlist_entry')
    op.drop_index(op.f('ix_watcher_source_name'), table_name='watcher_source')
    op.drop_table('watcher_source')
    # ### end Alembic commands ###

    for enum_name in ("watcheraccesstype", "conditionfloor", "wishliststatus"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
